export type Quote = {
    quote: string;
    correctAnswer: string;
  };
  
  export const quotes: Quote[] = [
    { quote: "Which team is nicknamed the Silver Arrows?", correctAnswer: "Mercedes" },
    { quote: "Which F1 team is based in Enstone, UK and has a rich French racing heritage?", correctAnswer: "Alpine" },
    { quote: "Which team has a prancing horse as its logo?", correctAnswer: "Ferrari" },
    { quote: "Which team has the longest continuous history in Formula 1, debuting in 1977?", correctAnswer: "Williams" },
    { quote: "Which team has won multiple Constructors' Championships thanks to its partnership with Honda?", correctAnswer: "Redbull" },
    { quote: "Which team is known for its papaya-colored cars?", correctAnswer: "Mclaren" },
    { quote: "Which team has won 8 consecutive Constructors' Championships from 2014 to 2021?", correctAnswer: "Mercedes" },
    { quote: "Which team has been home to legendary drivers like Michael Schumacher and Charles Leclerc?", correctAnswer: "Ferrari" },
    { quote: "Which team rebranded itself in 2021, carrying on the Renault legacy?", correctAnswer: "Alpine" },
    { quote: "Which team has claimed over 100 race victories but hasn’t won a Constructors' title since the 1990s?", correctAnswer: "Williams" },
    { quote: "Which team introduced the concept of high-rake aerodynamics to the modern grid?", correctAnswer: "Redbull" },
    { quote: "Which team’s headquarters are located in Woking, England?", correctAnswer: "Mclaren" },
    { quote: "Which team is often associated with Lewis Hamilton?", correctAnswer: "Mercedes" },
    { quote: "Which team’s cars are traditionally painted in Red?", correctAnswer: "Ferrari" },
    { quote: "Which team celebrated its first win in the turbo-hybrid era at the Hungarian Grand Prix in 2021?", correctAnswer: "Alpine" },
    { quote: "Which team has legendary British drivers like Nigel Mansell and Damon Hill as part of its history?", correctAnswer: "Williams" },
    { quote: "Which team features a bull in its logo?", correctAnswer: "Redbull" },
    { quote: "Which team partnered with Ayrton Senna during his championship-winning years?", correctAnswer: "Mclaren" },
    { quote: "Which team dominated F1 with their innovative DAS steering system?", correctAnswer: "Mercedes" },
    { quote: "Which team’s factory is located in Maranello, Italy?", correctAnswer: "Ferrari" },
    { quote: "Which team is backed by the automotive giant Renault?", correctAnswer: "Alpine" },
    { quote: "Which team is known for its iconic rivalry with Ferrari during the 1980s?", correctAnswer: "Mclaren" },
    { quote: "Which team achieved their first F1 victory at the Monaco Grand Prix in 2006?", correctAnswer: "Redbull" },
    { quote: "Which team has won the most Constructors' Championships in F1 history?", correctAnswer: "Ferrari" },
    { quote: "Which team’s cars are powered by Mercedes engines but carry a German automotive giant's name?", correctAnswer: "Mercedes" },
    { quote: "Which team secured its first podium finish with driver Esteban Ocon?", correctAnswer: "Alpine" },
    { quote: "Which team was famously sponsored by Martini during its recent F1 seasons?", correctAnswer: "Williams" },
    { quote: "Which team has Max Verstappen as its star driver?", correctAnswer: "Redbull" },
    { quote: "Which team introduced the MP4 series of cars, which dominated F1 in the 1980s and 1990s?", correctAnswer: "Mclaren" },
    { quote: "Which team is associated with the slogan 'The Best or Nothing'?", correctAnswer: "Mercedes" },
    { quote: "Which team has a rich history dating back to the 1929 Scuderia Ferrari racing stable?", correctAnswer: "Ferrari" },
    { quote: "Which team ran the FW14B car, one of the most dominant cars in F1 history?", correctAnswer: "Williams" },
    { quote: "Which team’s drivers are often called the ‘Red Bull Juniors’ before graduating to their main team?", correctAnswer: "Alpine" },
    { quote: "Which team’s drivers include legends like Ayrton Senna and Alain Prost?", correctAnswer: "Mclaren" },
    { quote: "Which team’s headquarters are located in Brackley, UK?", correctAnswer: "Mercedes" },
    { quote: "Which team’s engines were supplied by Honda until the end of 2021?", correctAnswer: "Redbull" },
    { quote: "Which team has Carlos Sainz as one of its drivers in 2024?", correctAnswer: "Ferrari" },
    { quote: "Which team earned its first Constructors' Championship in 1980?", correctAnswer: "Williams" },
    { quote: "Which team introduced the halo in F1 to improve driver safety?", correctAnswer: "Mercedes" },
    { quote: "Which team’s cars are known for their blue livery and Alpine branding?", correctAnswer: "Alpine" },
    { quote: "Which team competed with the MP4/4, considered one of the greatest F1 cars of all time?", correctAnswer: "Mclaren" },
    { quote: "Which team signed George Russell as a replacement for Valtteri Bottas?", correctAnswer: "Mercedes" },
    { quote: "Which team won the Constructors' Championship for the first time in 2010?", correctAnswer: "Redbull" },
    { quote: "Which team had Jacques Villeneuve win the Drivers' Championship in 1997?", correctAnswer: "Williams" },
    { quote: "Which team was led by Enzo Ferrari, the founder of the brand?", correctAnswer: "Ferrari" },
    { quote: "Which team’s drivers include Fernando Alonso and Esteban Ocon?", correctAnswer: "Alpine" },
    { quote: "Which team achieved a 1-2 finish at the 2023 Monaco Grand Prix?", correctAnswer: "Redbull" },
    { quote: "Which team switched from Honda to Mercedes engines in 2026?", correctAnswer: "Mclaren" },
    { quote: "Which team has been in Formula 1 since 1977 without missing a season?", correctAnswer: "Williams" },
    { quote: "Which team has a headquarters nicknamed ‘The MTC’?", correctAnswer: "Mclaren" },
    { quote: "Which team fielded Lewis Hamilton when he won his first Drivers' Championship?", correctAnswer: "Mclaren" },
    { quote: "Which team is synonymous with the Italian Grand Prix at Monza?", correctAnswer: "Ferrari" },
    { quote: "Which team won the 2021 Constructors' Championship?", correctAnswer: "Mercedes" },
    { quote: "Which team had a controversial rivalry with Mercedes throughout the 2021 season?", correctAnswer: "Redbull" },
    { quote: "Which team saw Esteban Ocon secure his first-ever F1 victory at the 2021 Hungarian Grand Prix?", correctAnswer: "Alpine" },
    { quote: "Which team’s driver, achieved his first-ever pole position during the 2021 Russian Grand Prix?", correctAnswer: "Mclaren" },
    { quote: "Which team ended their nine-year win drought by securing a 1-2 finish at the 2021 Italian Grand Prix?", correctAnswer: "Mclaren" },
    { quote: "Which team’s driver, George Russell, achieved his first podium at the 2021 Belgian Grand Prix under unusual circumstances?", correctAnswer: "Williams" },
    { quote: "Which team’s driver lineup in 2021 featured Charles Leclerc and Carlos Sainz?", correctAnswer: "Ferrari" },
    { quote: "Which team introduced their new title sponsor Aramco for the 2021 season?", correctAnswer: "Mercedes" },
    { quote: "Which team’s driver, Max Verstappen, won the 2021 Drivers' Championship after a dramatic final race?", correctAnswer: "Redbull" },
    { quote: "Which team’s car was designated the FW43B for the 2021 season?", correctAnswer: "Williams" },
    { quote: "Which team had a car called the MCL35M during the 2021 season?", correctAnswer: "Mclaren" },
    { quote: "Which team debuted Fernando Alonso's return to F1 in the 2021 season?", correctAnswer: "Alpine" },
    { quote: "Which team saw Sebastian Vettel claim a podium finish at the 2021 Azerbaijan Grand Prix?", correctAnswer: "Aston Martin" },
    { quote: "Which team’s drivers collided during the 2021 Emilia Romagna Grand Prix, taking both cars out of the race?", correctAnswer: "Williams" },
    { quote: "Which team introduced a special white livery for the Turkish Grand Prix in 2021?", correctAnswer: "Redbull" },
    { quote: "Which team finished third in the Constructors' Championship in the 2021 season?", correctAnswer: "Ferrari" },
    { quote: "Which team saw Valtteri Bottas win the Turkish Grand Prix in 2021?", correctAnswer: "Mercedes" },
    { quote: "Which team rebranded from Renault to its current name in 2021?", correctAnswer: "Alpine" },
    { quote: "Which team had the youngest driver pairing on the grid in 2021?", correctAnswer: "Williams" },
    { quote: "Which team had their car heavily criticized for a lack of competitiveness in 2021?", correctAnswer: "Haas" },
    { quote: "Which team introduced new rear wing upgrades during the 2021 Saudi Arabian Grand Prix?", correctAnswer: "Mercedes" },
    { quote: "Which team celebrated their 750th Grand Prix entry at the 2021 Monaco Grand Prix?", correctAnswer: "Ferrari" },
    { quote: "Which team featured a unique gulf livery at the 2021 Monaco Grand Prix?", correctAnswer: "Mclaren" },
    { quote: "Which team had its 2021 car designated as the RB16B?", correctAnswer: "Redbull" },
    { quote: "Which team scored the fastest lap during the final race of the 2021 season in Abu Dhabi?", correctAnswer: "Redbull" },
    { quote: "Which team saw Nicholas Latifi's crash in Abu Dhabi indirectly impact the 2021 Drivers' Championship?", correctAnswer: "Williams" },
    { quote: "Which team debuted Mick Schumacher in F1 during the 2021 season?", correctAnswer: "Haas" },
    { quote: "Which team introduced a car named the AMR21 in the 2021 season?", correctAnswer: "Aston Martin" },
    { quote: "Which team re-signed Lewis Hamilton for one year during the 2021 season?", correctAnswer: "Mercedes" },



  ];
  