export type Quote = {
    quote: string;
    correctAnswer: string;
  };
  
  export const quotes: Quote[] = [
  { quote: "We were on a break!", correctAnswer: "Ross" },
{ quote: "I’m a gym member. I try to go four times a week, but I’ve missed the last … twelve hundred times.",  correctAnswer: "Chandler"},
{ quote: "I tend to keep talking till somebody stops me.", correctAnswer: "Chandler"},
{ quote: "Well, maybe I don’t need your money. Wait, wait! I said, ‘Maybe.", correctAnswer: "Rachel" },
{ quote: "Should I use my invisibility to fight crime or for evil?.", correctAnswer: "Chandler"},
{ quote: "Welcome to the real world. It sucks. You’re gonna love it.", correctAnswer: "Monica" },
{ quote: "You don’t tell me what to do. I tell you what to do.", correctAnswer: "Monica" },
{ quote: "Isn't that just kick-you-in-the-crotch, spit-on-your-neck fantastic?", correctAnswer: "Rachel" },
{ quote: "Oh, I’m sorry. Did my back hurt your knife?", correctAnswer: "Rachel" },
{ quote: "How do we end up with these jerks? We’re good people", correctAnswer: "Rachel" },
{ quote: "Why do you have to break up with her? Be a man. Just stop calling.", correctAnswer: "Joey" },
{ quote: "I’m gonna go get one of those job things.", correctAnswer: "Rachel" },
{ quote: "It’s like there’s rock bottom, 50 feet of crap, then me.", correctAnswer: "Rachel" },
{ quote: "Oh, that’s okay, girls tend to not like me", correctAnswer: "Rachel" },
{ quote: "That's not even a word!", correctAnswer: "Monica" },
{ quote: "Pivot!", correctAnswer: "Ross" },
{ quote: "I honestly don’t know if I’m hungry or horny.", correctAnswer: "Ross" },
{ quote: "Ah. Humor based on my pain.", correctAnswer: "Ross" },
{ quote: "Not just health-department clean", correctAnswer: "Monica" },
{ quote: "I guess I’m not gonna be the mom who makes the world’s best chocolate cookies.", correctAnswer: "Monica" },
{ quote: "I tell you, when I actually die, some people are going to get seriously haunted.", correctAnswer: "Ross" },
{ quote: "Could I be wearing any more clothes?", correctAnswer: "Joey" },
{ quote: "The line is a dot to you!", correctAnswer: "Joey" },
{ quote: "I wish I could, but I don't want to.", correctAnswer: "Phoebe" },
{ quote: "'You're a shoe! You're a shoe! You're a shoe!'.", correctAnswer: "Rachel" },
{ quote: "Joey doesn't share food!", correctAnswer: "Joey" },
{ quote: "Seven! Seven! Seven!", correctAnswer: "Monica" },
{ quote: "Smelly cat, smelly cat, what are they feeding you?", correctAnswer: "Phoebe" },
{ quote: "Pivot!", correctAnswer: "Ross" },
{ quote: "Well, the fridge broke, so I had to eat everything.", correctAnswer: "Joey" },
{ quote: "These are just feelings. They’re gonna go away.", correctAnswer: "Joey" },
{ quote: "How you doin'?", correctAnswer: "Joey" },
{ quote: "I'm not great at the advice. Can I interest you in a sarcastic comment?", correctAnswer: "Chandler" },
{ quote: "See? He’s her lobster.", correctAnswer: "Phoebe" },
{ quote: "I got off the plane.", correctAnswer: "Rachel" },
{ quote: "Could I BE any more...?", correctAnswer: "Chandler" },
{ quote: "You can't just give up! Is that what a dinosaur would do?", correctAnswer: "Joey" },
{ quote: "I’m hopeless and awkward and desperate for love!", correctAnswer: "Chandler" },
{ quote: "I’m not so good with the advice. Can I interest you in a sarcastic comment?", correctAnswer: "Chandler" },
{ quote: "I don’t even have a 'pla'.", correctAnswer: "Phoebe" },
{ quote: "I say more dumb things before 9 a.m. than most people say all day.", correctAnswer: "Chandler"},
{ quote: "My eyes! My eyes!", correctAnswer: "Phoebe" },
{ quote: "Unagi is a state of total awareness.", correctAnswer: "Ross" },
{ quote: "I’m fine.", correctAnswer: "Ross" },
{ quote: "I don't even have a 'pla'.", correctAnswer: "Phoebe" },
{ quote: "I KNOW! I KNOW!", correctAnswer: "Monica" },
{ quote: "You can't just give up. Is that what a dinosaur would do?", correctAnswer: "Ross" },
{ quote: "Cheese. It’s milk that you chew.", correctAnswer: "Chandler" },
{ quote: "You are my Everest.", correctAnswer: "Chandler" },
{ quote: "I'm the holiday armadillo!", correctAnswer: "Ross" },
{ quote: "I stepped up! She’s my friend and she needed help!", correctAnswer: "Joey" },
{ quote: "Oh. My. God.", correctAnswer: "Janice" },
{ quote: "It's a moo point. It's like a cow's opinion; it doesn't matter. It's moo.", correctAnswer: "Joey" },
{ quote: "When I first meet somebody, it’s usually panic, anxiety and a great deal of sweating.", correctAnswer: "Chandler"},
{ quote: "You're over me? When were you... under me?", correctAnswer: "Ross" },
{ quote: "I make jokes when I'm uncomfortable.", correctAnswer: "Chandler" },
{ quote: "No uterus, no opinion.", correctAnswer: "Rachel" },
{ quote: "You hung up on the pizza place? I don’t hang up on your friends.", correctAnswer: "Joey" },
{ quote: "My wallet’s too small for my fifties, and my diamond shoes are too tight.", correctAnswer: "Chandler" },
{ quote: "Monica, stop staring at me. You’re freaking me out.", correctAnswer: "Phoebe" },
  ];
  