export type Quote = {
  quote: string;
  correctAnswer: string;
};

export const quotes: Quote[] = [
  { quote: "Which team is co-owned by Shah Rukh Khan?", correctAnswer: "KKR" },
  { quote: "Which team has won the most IPL titles?", correctAnswer: "MI" },
  { quote: "Which team is known for their captain MS Dhoni?", correctAnswer: "CSK" },
  { quote: "Which team plays their home games at the Sawai Mansingh Stadium in Jaipur?", correctAnswer: "RR" },
  { quote: "Which team is famous for the slogan 'Ee Sala Cup Namde'?", correctAnswer: "RCB" },
  { quote: "Which team represents the state of Punjab?", correctAnswer: "PK" },
  { quote: "Which team is called the 'Orange Army'?", correctAnswer: "SRH" },
  { quote: "Which team was previously known as Delhi Daredevils?", correctAnswer: "DC" },
  { quote: "Which team is associated with Wankhede Stadium?", correctAnswer: "MI" },
  { quote: "Which team has a lion as their mascot?", correctAnswer: "CSK" },
  { quote: "Which team is associated with the Eden Gardens stadium?", correctAnswer: "KKR" },
  { quote: "Which team has never won the IPL despite having Virat Kohli?", correctAnswer: "RCB" },
  { quote: "Which team is known for their pink jersey?", correctAnswer: "RR" },
  { quote: "Which team is co-owned by Preity Zinta?", correctAnswer: "PK" },
  { quote: "Which team won the IPL trophy in its debut season?", correctAnswer: "RR" },
  { quote: "Which team has David Warner as one of its most iconic players?", correctAnswer: "SRH" },
  { quote: "Which team has their home ground at Feroz Shah Kotla?", correctAnswer: "DC" },
  { quote: "Which team is known as the 'Men in Yellow'?", correctAnswer: "CSK" },
  { quote: "Which team’s jersey features purple and gold colors?", correctAnswer: "KKR" },
  { quote: "Which team has Rohit Sharma as their most successful captain?", correctAnswer: "MI" },
  { quote: "Which team is known as the 'Whistle Podu' team?", correctAnswer: "CSK" },
  { quote: "Which team has Virat Kohli as their star player and former captain?", correctAnswer: "RCB" },
  { quote: "Which team won the inaugural IPL tournament in 2008?", correctAnswer: "RR" },
  { quote: "Which team has the nickname 'Kolkata Knight Riders'?", correctAnswer: "KKR" },
  { quote: "Which team is represented by the Sun in its logo?", correctAnswer: "SRH" },
  { quote: "Which team was the IPL champion in 2022 with Hardik Pandya as captain?", correctAnswer: "GT" },
  { quote: "Which team has the nickname 'Delhi Capitals'?", correctAnswer: "DC" },
  { quote: "Which team has the nickname 'Punjab Kings'?", correctAnswer: "PK" },
  { quote: "Which team is associated with the slogan 'Ee Sala Cup Namde'?", correctAnswer: "RCB" },
  { quote: "Which team is co-owned by Bollywood star Shahrukh Khan?", correctAnswer: "KKR" },
  { quote: "Which team has MS Dhoni as their iconic captain?", correctAnswer: "CSK" },
  { quote: "Which team represents the city of Hyderabad?", correctAnswer: "SRH" },
  { quote: "Which team is known for its record five IPL titles?", correctAnswer: "MI" },
  { quote: "Which team had Chris Gayle as one of their star players?", correctAnswer: "RCB" },
  { quote: "Which team was known as Kings XI Punjab before being renamed?", correctAnswer: "PK" },
  { quote: "Which team was captained by Shane Warne in their first IPL victory?", correctAnswer: "RR" },
  { quote: "Which team changed its name to Delhi Capitals in 2019?", correctAnswer: "DC" },
  { quote: "Which team is known for their captain MS Dhoni?", correctAnswer: "CSK" },
  { quote: "Which team plays their home games at the Sawai Mansingh Stadium in Jaipur?", correctAnswer: "RR" },
  { quote: "Which team is famous for the slogan 'Ee Sala Cup Namde'?", correctAnswer: "RCB" },
  { quote: "Which team represents the state of Punjab?", correctAnswer: "PK" },
  { quote: "Which team is called the 'Orange Army'?", correctAnswer: "SRH" },
  { quote: "Which team was previously known as Delhi Daredevils?", correctAnswer: "DC" },
  { quote: "Which team is associated with Wankhede Stadium?", correctAnswer: "MI" },
  { quote: "Which team has a lion as their mascot?", correctAnswer: "CSK" },
  { quote: "Which team is associated with the Eden Gardens stadium?", correctAnswer: "KKR" },
  { quote: "Which team had Chris Gayle as one of their star players?", correctAnswer: "RCB" },
  { quote: "Which team was known as Kings XI Punjab before being renamed?", correctAnswer: "PK" },
  { quote: "Which team was captained by Shane Warne in their first IPL victory?", correctAnswer: "RR" },
  { quote: "Which team changed its name to Delhi Capitals in 2019?", correctAnswer: "DC" },
  { quote: "Which team had the nickname 'Deccan Chargers' before being replaced by SRH?", correctAnswer: "SRH" },
  { quote: "Which team has Jasprit Bumrah as their star bowler?", correctAnswer: "MI" },
{ quote: "Which team is associated with the tagline 'Rise and Roar'?", correctAnswer: "CSK" },
{ quote: "Which team is nicknamed 'Halla Bol'?", correctAnswer: "RR" },
{ quote: "Which team introduced the 'Fan Wall' feature for virtual fan interaction?", correctAnswer: "RCB" },
{ quote: "Which team is associated with the tagline 'Aava De'?", correctAnswer: "GT" },
{ quote: "Which team won the IPL title in their debut season (2022)?", correctAnswer: "GT" },
{ quote: "Which team plays their home matches at the Narendra Modi Stadium?", correctAnswer: "GT" },
{ quote: "Which team defeated Rajasthan Royals to win their first IPL title?", correctAnswer: "GT" },
{ quote: "Which team is captained by Hardik Pandya during IPL 2022?", correctAnswer: "GT" },
{ quote: "Which team is known for its slogan 'We Play to Win'?", correctAnswer: "GT" },
{ quote: "Which team had a successful debut by topping the IPL 2022 points table?", correctAnswer: "GT" },
{ quote: "Which team is associated with the tagline 'Sadda Punjab'?", correctAnswer: "PK" },

{ quote: "Which team plays their home matches at the Punjab Cricket Association IS Bindra Stadium?", correctAnswer: "PK" },
{ quote: "Which IPL team is known for its strong connection with fans through the slogan 'Sadda Squad'?", correctAnswer: "PK" },
{ quote: "Which team reached the IPL final in 2014 but lost to KKR?", correctAnswer: "PK" },
{ quote: "Which team has won the IPL title in both 2012 and 2014?", correctAnswer: "KKR" },
{ quote: "Which team was captained by Gautam Gambhir during their IPL title wins?", correctAnswer: "KKR" },
{ quote: "Which team introduced the 'Knight Club' fan engagement initiative?", correctAnswer: "KKR" }

];
